const LBRHE = {
  META: {
    title: 'Racial & Health Equity in Long Beach',
    subtitle: 'A reading of the 2023 American Community Survey, narrowed to four neighborhoods and the people inside them.',
    partner: 'City of Long Beach · Department of Health & Human Services',
    community: 'Long Beach – Compton Data Science Learning Community',
    symposium: 'CSULB Student Research Symposium · Poster #28 · September 2025',
    faculty: 'Faculty Mentor: Dr. Seungjoon Lee (CSULB)',
    team: [
      { name: 'Marine Karapetyan', affil: 'LBUSD / LBCC', role: 'Team Lead' },
      { name: 'Dr. Seungjoon Lee', affil: 'CSULB', role: 'Team Lead · Faculty' },
      { name: 'Nicholas Andrade', affil: 'CSULB', role: 'Technical Lead' },
      { name: 'Robby Born', affil: 'CSULB', role: 'Technical Lead' },
      { name: 'Andy Molina', affil: 'CSULB', role: 'Data Scientist' },
      { name: 'Michelle Ibanez', affil: 'LBCC', role: 'Researcher' },
      { name: 'John Seng', affil: 'LBCC', role: 'Researcher' },
      { name: 'Torriano Knight', affil: 'LACC', role: 'Researcher' },
      { name: 'Hernan Zelaya', affil: 'LACC', role: 'Researcher' },
    ],
    data: {
      rows: '5,000,000+',
      variables: '500+',
      source: 'U.S. Census Bureau, American Community Survey 1-Year Estimates · 2021 + 2023',
      method: 'Public Use Microdata Sample (PUMS) via the tidycensus package in R',
    },
  },
  DEMOGRAPHICS: {
    race: [
      { group: 'Latinx', pct: 41 },
      { group: 'White', pct: 30 },
      { group: 'AAPI', pct: 15 },
      { group: 'Black', pct: 9 },
      { group: 'Other', pct: 5 },
    ],
    income_class: [
      { group: 'Lower ($<40K)', pct: 20 },
      { group: 'Lower-middle ($40–70K)', pct: 15 },
      { group: 'Middle ($70–140K)', pct: 31 },
      { group: 'Upper-middle ($140–250K)', pct: 20 },
      { group: 'Affluent ($250K+)', pct: 11 },
    ],
    education: [
      { group: 'No HS diploma', pct: 15.5 },
      { group: 'HS diploma', pct: 20.7 },
      { group: 'Some college', pct: 24.0 },
      { group: 'AA/AS degree', pct: 6.2 },
      { group: 'BA or higher', pct: 33.5 },
    ],
  },
  POVERTY: {
    race: [
      { group: 'Black', pct: 27 },
      { group: 'Latino', pct: 16 },
      { group: 'Other', pct: 16 },
      { group: 'AAPI', pct: 13 },
      { group: 'White', pct: 12 },
    ],
    hisp: [
      { group: 'Honduran', pct: 43 },
      { group: 'other Latino', pct: 26 },
      { group: 'Salvadoran', pct: 19 },
      { group: 'Latino (all)', pct: 16 },
      { group: 'Mexican', pct: 15 },
      { group: 'Guatemalan', pct: 14 },
    ],
    aapi: [
      { group: 'Korean', pct: 34 },
      { group: 'Other Asian', pct: 25 },
      { group: 'Chinese', pct: 20 },
      { group: 'Filipino', pct: 15 },
      { group: 'Asian / PI', pct: 14 },
      { group: 'Indian', pct: 12 },
      { group: 'Japanese', pct: 12 },
      { group: 'Cambodian', pct: 10 },
    ],
  },
  EDUCATION_LT_HS: {
    hisp: [
      { group: 'Salvadoran', pct: 56 },
      { group: 'Guatemalan', pct: 56 },
      { group: 'Honduran', pct: 53 },
      { group: 'Mexican', pct: 45 },
      { group: 'other Latino', pct: 23 },
    ],
    aapi: [
      { group: 'Vietnamese', pct: 51 },
      { group: 'Cambodian', pct: 40 },
      { group: 'Korean', pct: 39 },
      { group: 'Other Asian', pct: 38 },
      { group: 'Japanese', pct: 22 },
      { group: 'Chinese', pct: 18 },
      { group: 'Filipino', pct: 14 },
      { group: 'Indian', pct: 7 },
      { group: 'Pacific Isld.', pct: 6 },
    ],
  },
  MEDICAID: [
    { group: 'Other', pct: 38 },
    { group: 'Black', pct: 38 },
    { group: 'Latinx', pct: 37 },
    { group: 'AAPI', pct: 25 },
    { group: 'White', pct: 13 },
  ],
  UNINSURED: [
    { group: 'White', pct: 4 },
    { group: 'Black', pct: 3 },
    { group: 'Latinx', pct: 10 },
    { group: 'AAPI', pct: 4 },
    { group: 'Other', pct: 3 },
  ],
  HH_INCOME: [
    { group: 'White', k: 110 },
    { group: 'AAPI', k: 105 },
    { group: 'Other', k: 98 },
    { group: 'Latinx', k: 90 },
    { group: 'Black', k: 56 },
  ],
  UNEMPLOY: [
    { group: 'Black', pct: 7.3 },
    { group: 'Other', pct: 7.0 },
    { group: 'Latino', pct: 6.3 },
    { group: 'White', pct: 5.8 },
    { group: 'AAPI', pct: 5.1 },
  ],
  VARIABLES: {
    global: [
      { code: 'RAC1P/RAC3P/HISP', label: 'Race' },
      { code: 'AGEP', label: 'Age' },
      { code: 'SEX', label: 'Sex' },
      { code: 'PUMA', label: 'Location' },
    ],
    equity: [
      { code: 'SCHL', label: 'Educational attainment' },
      { code: 'POVPIP', label: 'Poverty-to-income ratio' },
      { code: 'PINCP', label: 'Personal income' },
      { code: 'HINCP', label: 'Household income' },
      { code: 'VALP', label: 'Property value' },
      { code: 'HICOV', label: 'Health insurance' },
      { code: 'HINS4', label: 'Medicaid' },
      { code: 'ESR', label: 'Employment status' },
      { code: 'PAP', label: 'Public assistance income' },
      { code: 'HHT2', label: 'Household type' },
      { code: 'DIS', label: 'Disability' },
      { code: 'ACCESSINET', label: 'Internet access' },
      { code: 'FS', label: 'Food stamp / SNAP' },
    ],
  },
  TIMELINE: [
    { phase: 'I', step: 'Data extraction', detail: 'Pulled PUMS microdata for the four Long Beach PUMAs from the U.S. Census API via R\'s tidycensus, restricted to 2021 + 2023.' },
    { phase: 'II', step: 'Data wrangling', detail: 'Narrowed 500+ variables to the 17 that map to lived equity. Recoded continuous age into five life-stage bins; binned household income into five economic classes.' },
    { phase: 'III', step: 'Data analysis', detail: 'Cross-tabulated each equity variable against race, ethnicity, and PUMA. Compared 2021 ↔ 2023 to surface change rather than just state.' },
    { phase: 'IV', step: 'Visualization', detail: 'Authored five interactive Tableau dashboards — one per region plus a city-wide poverty/employment/Medicaid view — alongside two community-facing infographics.' },
  ],
  TABLEAU_LINKS: [
    { region: 'City-wide', title: 'Unemployment · Tenure · Medicaid Dashboard', href: 'https://public.tableau.com/app/profile/nicholas.andrade6176/viz/UnemploymentTenureMedicaidDashboard/PovertyDashboard#1' },
    { region: 'Central', title: 'Furthers Talong — Central Long Beach', href: 'https://public.tableau.com/views/Furtherstalong/Centeral' },
    { region: 'Southwest', title: 'Furthers Talong — Southwest Long Beach', href: 'https://public.tableau.com/views/Furtherstalong/Southwest' },
    { region: 'East', title: 'Furthers Talong — East Long Beach', href: 'https://public.tableau.com/views/Furtherstalong/East' },
    { region: 'North', title: 'Furthers Talong — North Long Beach', href: 'https://public.tableau.com/views/Furtherstalong/North' },
    { region: 'Modern', title: 'Furthers Talong — Modern view', href: 'https://public.tableau.com/views/Furtherstalong/Modern' },
  ],
  ANDY_CONTRIBUTION: [
    'Co-authored the data extraction pipeline in R: parameterized the PUMS pulls so the team could re-run any region for any year with one call.',
    'Built the variable dictionary that mapped 500+ raw PUMS codes onto a 17-variable equity schema, including the household-income → class binning the dashboards now hinge on.',
    'Designed the recoding logic for age categories (Under 5 / 5–17 / 18–24 / 25–64 / 65+) used across every regional dashboard.',
    'Joint authorship of the city-wide infographic; presented poster #28 at the CSULB Student Research Symposium, 19 September 2025.',
  ],
};

export { LBRHE };
